version: '3.3'
services:
  mariadb:
    image: mariadb:11.1.2
    container_name: t7-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
    volumes:
      - tarea7-data:/var/lib/mysql
    ports:
      - "3306:3306"

  tomcat:
    image: tomcat:10.1.9-jdk17
    container_name: t7-tomcat
    ports:
      - "8081:8081"
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war

  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.0
    container_name: t7-cloudbeaver
    ports:
      - "8978:8978"

volumes:
  tarea7-data:
